language: cpp
dist: bionic
sudo: false
os:  linux

before_install:
- echo $LANG
- echo $LC_ALL

notifications:
  email: false

compiler:
  - clang
  - gcc


addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-7
      - clang-7
      - libboost-all-dev

script: 
  - mkdir build
  - cd build
  - cmake ..
  - cmake --build .
