language: cpp
dist: bionic
sudo: false
os:  linux

before_install:
- echo $LANG
- echo $LC_ALL

notifications:
  email: false

compiler:
  - clang
  - gcc

install:
  - sudo apt-get install libboost-all-dev
  - sudo apt install clang-6.0
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test
  - sudo apt-get update
  - sudo apt-get install gcc-8 g++-8

script: 
  - mkdir build
  - cd build
  - cmake ..
  - cmake --build .
