language: cpp
dist: bionic
sudo: false
os:  linux

before_install:
- echo $LANG
- echo $LC_ALL

notifications:
  email: false

compiler: gcc


addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-10
      - g++-10
      - libboost-all-dev

script: 
  - export CC=gcc-10
  - export CXX=g++-10
  - mkdir build
  - cd build
  - cmake ..
  - cmake --build .
  - ./test/unit_tests
  - sudo dpkg -i package.deb
  - litesh -h
  - fctrl -h
