language: cpp
dist: bionic
sudo: false
os:  linux

before_install:
- echo $LANG
- echo $LC_ALL

notifications:
  email: false

compiler:
  - clang
  - gcc

install:
  - sudo apt-get install libboost-all-dev

script: 
  - mkdir build
  - cd build
  - cmake ..
  - cmake --build .
