language: cpp
dist: bionic
sudo: false
os:  linux

before_install:
- echo $LANG
- echo $LC_ALL

notifications:
  email: false

compiler:
  - clang
  - gcc

script: 
  - mkdir build
  - cd build
  - cmkae ..
  - cmkae --build
